FROM registry.gitlab.com/qontainers/pipglr:latest

MAINTAINER Christoph Kappel <christoph@unexist.dev>

ARG PODNAME
ARG REGISTRY_URL

# FIXME: We have to redefine the label - unfortunately passing args to the next stage doesn't
#        work as expected and we additionally have to add the name of the pod
ARG DEFAULT_JOB_IMAGE=registry.fedoraproject.org/fedora-minimal:latest
ARG GITLAB_URL
ARG NESTED_PRIVILEGED=true

# FIXME: Weird issues with permissions with newuidmap as normal user on Debian 12 - so we run everything as root for now
# https://github.com/containers/podman/issues/15370
RUN mv -f /home/podman/.config/systemd/user/*.{service,socket,timer} /etc/systemd/system \
    && chown root:root /etc/systemd/system/* \
    && rm -rf home/podman/.config/systemd/user \
    && mkdir -p /etc/systemd/system/{sockets.target.wants,default.target.wants} \
    && ln -s /etc/systemd/system/podman.socket /etc/systemd/system/sockets.target.wants/ \
    && ln -s /etc/systemd/system/prune.timer /etc/systemd/system/default.target.wants/

# Add insecure registry
# FIXME: Heredoc requires Podmman >4.8
RUN echo -e "[[registry]]\nlocation = \"${REGISTRY_URL}\"\ninsecure = true" > /etc/containers/registries.conf.d/gitlab.conf \
    && sed -i -e "s#localhost#gitlab#" /etc/containers/registries.conf.d/gitlab.conf

RUN curl -sL --retry 3 https://dl.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin sh

LABEL register="podman run -it --rm --pod=${PODNAME} \
    --secret=REGISTRATION_TOKEN,type=env \
    -v ./config.toml:/etc/gitlab-runner/config.toml:Z \
    -v ./gitlab.crt:/etc/gitlab-runner/certs/gitlab.crt \
    -e REGISTER_NON_INTERACTIVE=true \
    -e CI_SERVER_URL=https://${GITLAB_URL} \
    -e CI_SERVER_TLS_CA_FILE=/etc/gitlab-runner/certs/gitlab.crt \
    -e CLONE_URL=https://${GITLAB_URL} \
    -e RUNNER_NAME=pipglr \
    -e RUNNER_EXECUTOR=docker \
    -e RUNNER_SHELL=bash \
    -e DOCKER_HOST=unix:///home/runner/podman.sock \
    -e DOCKER_IMAGE=${DEFAULT_JOB_IMAGE} \
    -e DOCKER_CACHE_DIR=/cache \
    -e DOCKER_VOLUMES=/cache \
    -e DOCKER_NETWORK_MODE=host \
    -e DOCKER_PRIVILEGED=${NESTED_PRIVILEGED} \
    -e DOCKER_TLS_VERIFY=false \
    --entrypoint=/usr/bin/gitlab-runner \$IMAGE register"

LABEL dumpconfig="podman run -it --rm --pod=${PODNAME} \
    --secret config.toml --entrypoint=/bin/cat \
    \$IMAGE /var/run/secrets/config.toml"

LABEL run="podman run -dit --name pipglr --pod=${PODNAME} \
    --secret config.toml,uid=1001,gid=1001 \
    -v ./config.toml:/etc/gitlab-runner/config.toml:Z \
    -v ./gitlab.crt:/etc/gitlab-runner/certs/gitlab.crt \
    -v pipglr-storage:/home/podman/.local/share/containers \
    -v pipglr-cache:/cache \
    --systemd true \
    --privileged \
    --device /dev/fuse:rw \$IMAGE"